---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-12-10T03:13:17Z"
  namespace: assisted-installer
  labels:
    app: assisted-installer
  name: assisted-installer
spec:
  ports:
  - name: "8000"
    nodePort: 32298
    port: 8000
    protocol: TCP
    targetPort: 0
  - name: "8090"
    nodePort: 30650
    port: 8090
    protocol: TCP
    targetPort: 0
  - name: "8080"
    nodePort: 32047
    port: 8080
    protocol: TCP
    targetPort: 0
  selector:
    app: assisted-installer
  type: NodePort
status:
  loadBalancer: {}
